"""Kurze, fachlich vorsichtige Texte der zweisprachigen Oberfläche."""

TEXT = {
    "de": {
        "tagline": "Wöchentliche Sichtung für unterstützende Gespräche",
        "language": "Sprache / Language",
        "help_button": "Hilfe & Hintergrund",
        "help_title": "Hilfe und Projektwissen",
        "help_quick": "Bedienung & Glossar",
        "help_background": "Über die Demo",
        "help_start": "So nutzt du die Übersicht",
        "help_steps": "1. Wochen-CSV hochladen und Kurstag wählen.\n2. Im Kurs eine Prüfliste fachlich sichten und ein passendes Unterstützungsangebot wählen.\n3. Unter Leitung den möglichen Zeitbedarf für Sichtung, Nachrichten und Gespräche planen. Tatsächliche Kontakte im dafür vorgesehenen Betreuungssystem dokumentieren.",
        "glossary": "Glossar",
        "limitations": "Was der Prototyp nicht weiß",
        "limits_text": "Das Modell ordnet Kurseinträge nach einem gemeinsamen späteren Ergebnis: Abbruch oder Nichtbestehen. Es erkennt nicht verlässlich, welche Art von Schwierigkeit eine einzelne Person hat. Beobachtete Klicks und Leistungen erklären keinen persönlichen Grund; die Wirkung eines Gesprächs wurde nicht geprüft. Die historischen OULAD-Modelle sind für andere Weiterbildungen nicht validiert.",
        "theme_help": "Heller oder dunkler Modus: Oben rechts im Streamlit-Menü (⋮) Einstellungen → Theme wählen. Für größere Schrift kannst du die Browser-Zoomfunktion nutzen (Strg und +). Prüfe die Ansicht auch bei 200 % Zoom.",
        "gloss_csv": "CSV: Textdatei mit tabellarischen Daten. Hier muss sie das vorbereitete Wochenformat enthalten.",
        "gloss_vle": "VLE (Virtual Learning Environment): virtuelle Lernumgebung. Klicks zeigen erfasste Nutzung, nicht Lernzeit oder Verständnis.",
        "gloss_assessment": "Assessment: im Kurs vorgesehene Leistung. Als offen gilt eine fällige Leistung ohne erfasste eigene oder angerechnete Erfüllung.",
        "gloss_entry": "Kurseintrag: Teilnahme einer Person an einem bestimmten Kursdurchlauf. Eine Person kann mehrere Einträge haben.",
        "gloss_course": "Kursdurchlauf: ein Modul in einer bestimmten Präsentation, z. B. BBB 2014J.",
        "gloss_hint": "Prüfliste: Auswahl für die fachliche Sichtung. 10 % oder 20 % bedeutet, wie viele Personen eines Kurses an diesem Kurstag ausgewählt werden (bei kleinen Kursen aufgerundet). Die Auswahl ist keine feste Risikoschwelle. Auch Personen außerhalb der Liste können abbrechen oder nicht bestehen.",
        "gloss_first": "Neu auf Liste: In keiner früheren Woche dieser hochgeladenen CSV stand der Eintrag auf der gerade gewählten kurzen oder erweiterten Liste. Schon früher: mindestens einmal zuvor auf derselben Listenart. Die App weiß nicht, ob die Person kontaktiert wurde.",
        "gloss_ap": "AP (Average Precision): bewertet, wie gut spätere Fälle in der gesamten Modellreihenfolge weit oben stehen. Eine Kennzahl zur Modellauswertung, nicht für Einzelpersonen.",
        "gloss_recall": "Recall: Anteil aller späteren Fälle, die eine Prüfliste erreicht. Eine Kennzahl zur Modellauswertung.",
        "gloss_score": "Modellwert: interner Wert zum Sortieren innerhalb des Kurses; hier keine geprüfte individuelle Ausfallwahrscheinlichkeit.",
        "bug_button": "Fehler melden",
        "bug_title": "Fehlerbericht vorbereiten",
        "bug_intro": "Beschreibe, was nicht funktioniert hat. Der Bericht wird lokal heruntergeladen und nicht automatisch gesendet.",
        "bug_expected": "Was hast du erwartet?",
        "bug_observed": "Was ist stattdessen passiert?",
        "bug_steps": "Wie lässt sich der Fehler wiederholen?",
        "bug_privacy": "Bitte keine Namen, Lernenden-IDs, Kursdateien oder anderen personenbezogenen Daten eintragen. Ein öffentliches GitHub-Issue ist für solche Daten ungeeignet.",
        "bug_download": "Fehlerbericht herunterladen",
        "bug_missing": "Beschreibe zunächst, was passiert ist.",
        "bug_issue": "GitHub-Issue öffnen (optional)",
        "data_title": "Daten bereitstellen",
        "change_data": "Datei wechseln",
        "data_intro": "Lade eine vorbereitete Wochen-CSV hoch. Für die Vorführung kannst du die Beispieldatei herunterladen und hier auswählen.",
        "demo_download": "Vorführdatei herunterladen",
        "upload_label": "Wochen-CSV auswählen",
        "upload_help": "Eine Zeile je angemeldetem Kurseintrag und Kurstag. Für eine vollständige Prüfliste muss der ganze Kurs enthalten sein. Die OULAD-Rohdateien müssen zuvor aufbereitet werden.",
        "no_upload": "Nach dem Upload kannst du einen Kurstag wählen und die Prüflisten öffnen.",
        "load_spinner": "Datei prüfen und Hinweise berechnen …",
        "model_error": "Die Modellbewertung ist fehlgeschlagen. Details stehen im Terminal.",
        "upload_error": "Die hochgeladene Datei konnte nicht verarbeitet werden. Technische Details stehen unten.",
        "technical_details": "Technische Details (derzeit auf Deutsch)",
        "loaded": "{n} Wochenstände aus {file} eingelesen.",
        "day_label": "Kurstag auswählen",
        "day_option": "Tag {day} · Woche {week}",
        "history_unknown": "Für diesen Kurstag enthält die Datei keinen früheren Wochenstand. Ob eine Person zuvor schon auf einer Prüfliste stand, ist nicht bekannt.",
        "history_known": "Neu auf Liste = in keiner früheren Woche dieser Datei auf der gewählten kurzen oder erweiterten Prüfliste. Schon früher = mindestens einmal zuvor auf derselben Listenart. Die App kennt keine geführten Gespräche.",
        "nav": "Bereich",
        "nav_week": "🗓️ Diese Woche",
        "nav_course": "👥 Kurs prüfen",
        "nav_manager": "📊 Leitung & Kapazität",
        "nav_background": "📚 Über das Projekt",
        "week_intro": "Wähle einen Kurs, dessen Hinweise du fachlich prüfen möchtest.",
        "metric_entries": "Aktuelle Kurseinträge",
        "metric_courses": "Kurse",
        "metric_hints": "Auf Prüflisten",
        "metric_hints_help": "Oberste 20 % der Kurseinträge je Kursdurchlauf, auf ganze Personen aufgerundet.",
        "col_course": "Kurs",
        "col_entries": "Kurseinträge",
        "col_review": "Zur Sichtung",
        "col_first": "Neu auf Liste",
        "col_repeat": "Schon früher auf Liste",
        "col_first_help": "Für diese Personen gab es in keiner früheren Woche der hochgeladenen Datei einen Hinweis.",
        "col_repeat_help": "Für diese Personen gab es in mindestens einer früheren Woche der hochgeladenen Datei schon einen Hinweis. Das sagt nichts über einen tatsächlichen Kontakt aus.",
        "col_due": "Mit offener fälliger Leistung",
        "col_due_help": "Mindestens eine fällige Leistung ohne erfasste eigene oder angerechnete Erfüllung.",
        "col_review_help": "Oberste 20 % der Modellreihenfolge in diesem Kurs; keine feste Risikogrenze.",
        "course_choose": "Kurs für die Prüfliste",
        "open_list": "Prüfliste öffnen",
        "trend_open": "Prüflisten je Woche (alle Kurse)",
        "trend_intro": "Pro Zeile siehst du, wie viele Kurseinträge in dieser Woche erstmals oder schon früher innerhalb dieser Datei auf einer Prüfliste standen.",
        "trend_day": "Kurstag",
        "trend_caption": "Eine Person kann in mehreren Wochen vorkommen. Addiere die Wochenzahlen daher nicht als Anzahl verschiedener Personen. Kontakte oder Gespräche werden hier nicht erfasst.",
        "course_title": "Kurs prüfen",
        "course_label": "Kursdurchlauf",
        "course_caution": "Die Liste hilft bei der fachlichen Sichtung. Ein Hinweis ist keine Diagnose und keine geprüfte persönliche Ausfallwahrscheinlichkeit.",
        "scope_label": "Wie viele Personen möchtest du prüfen?",
        "scope_more": "Mehr Personen prüfen: {n} von {total} (oberste rund 20 %)",
        "scope_less": "Weniger Personen prüfen: {n} von {total} (oberste rund 10 %)",
        "scope_help": "Die 10-%-Liste enthält die obersten Plätze dieses Kurses an diesem Kurstag. Die 20-%-Liste enthält dieselben Personen und die nächsten Plätze. Bei kleinen Kursen wird aufgerundet. Jede Woche wird neu bewertet: Über mehrere Wochen können mehr als 20 % irgendwann einen Hinweis erhalten.",
        "scope_caption": "Du siehst {n} von {total} Personen in diesem Kurs. Die übrigen {remaining} stehen heute nicht auf dieser Prüfliste, können später aber ebenfalls abbrechen oder nicht bestehen. Die Quote begrenzt nur, wie viele Personen du jetzt sichtest; sie ist keine persönliche Ausfallwahrscheinlichkeit.",
        "scope_evidence_title": "Wie viele spätere Fälle fanden die Listen im historischen Vergleich?",
        "scope_evidence": "Beispiel Tag 27 in 2014J: Die 20-%-Listen enthielten 1.006 von 2.947 späteren Fällen (34,1 %). 1.941 spätere Fälle standen an diesem Tag nicht darauf. Die 10-%-Listen enthielten 595 Fälle (20,2 %). Das ist eine explorative historische Auswertung, keine Zusage für diesen Kurs oder eine andere Einrichtung. Auch wiederholte wöchentliche Sichtungen ersetzen die fachliche Prüfung nicht.",
        "filter_label": "Hinweise anzeigen",
        "filter_all": "Alle",
        "filter_first": "Neu auf Liste",
        "filter_repeat": "Schon früher auf Liste",
        "list_summary": "{n} von {total} Kurseinträgen auf dieser Prüfliste.",
        "list_empty": "Für diesen Filter gibt es an diesem Kurstag keine Hinweise.",
        "col_id": "Anonymisierte ID",
        "col_group": "Prüfgruppe",
        "group_high": "Zuerst sichten",
        "group_more": "Weitere Sichtung",
        "col_status": "Listenverlauf in Datei",
        "status_first": "Neu auf Liste",
        "status_repeat": "Schon früher auf Liste",
        "status_unknown": "Kein früherer Wochenstand",
        "status_none": "Kein Hinweis",
        "col_id_help": "Anonymisierte Kennung eines Kurseintrags; die App kennt keinen Namen.",
        "col_group_help": "Reihenfolge aus dem Modell innerhalb dieses Kursdurchlaufs; keine Diagnose.",
        "col_status_help": "Neu heißt: in keiner früheren Woche dieser CSV auf der gerade gewählten Listenart. Schon früher heißt: mindestens einmal zuvor auf derselben Listenart. Über Kontakte liegen keine Angaben vor.",
        "col_missing": "Fällige Leistungen ohne Erfüllung",
        "col_clicks": "Plattformklicks letzte 7 Tage",
        "col_clicks_help": "Erfasste VLE-Klicks der letzten sieben Kurstage; keine Messung von Lernzeit oder Verständnis.",
        "person_choose": "Person genauer ansehen",
        "detail_title": "ID {id} · Beobachtungen bis Tag {day}",
        "due_observation": "{n} fällige Leistung(en) ohne erfasste Abgabe oder Anrechnung.",
        "due_question": "Ist die Leistung abgegeben, angerechnet oder noch in Klärung?",
        "zero_observation": "Keine erfassten Plattformklicks in den letzten sieben Tagen.",
        "zero_question": "Gab es Zugangsprobleme oder Lernen außerhalb der Plattform?",
        "low_observation": "Weniger Plattformklicks als der Median dieses Kursdurchlaufs in den letzten sieben Tagen.",
        "no_observation": "Keines dieser einfachen Einzelmerkmale fällt auf. Der Modellhinweis nutzt eine Kombination von Angaben.",
        "conversation": "Für ein unterstützendes Gespräch prüfen",
        "general_question": "Welche Unterstützung wäre aus Sicht der Person hilfreich?",
        "detail_limit": "Diese Beobachtungen erklären weder den Modellwert noch die persönliche Situation. Abbruch und Nichtbestehen werden gemeinsam vorhergesagt.",
        "next_step_title": "Nächsten Schritt wählen",
        "next_step_first": "Prüfe den Kurseintrag fachlich. Wenn ein Angebot sinnvoll ist, beginne mit einer kurzen, wertfreien Nachricht und biete Hilfe an.",
        "next_step_due": "Prüfe zuerst, ob die fällige Leistung wirklich offen ist. Wenn die Person Unterstützung wünscht oder eine Aufgabe bald geklärt werden muss, biete ein persönliches Gespräch an.",
        "next_step_repeat": "Dieser Eintrag stand schon früher in der hochgeladenen Datei auf einer Prüfliste. Prüfe zuerst im Betreuungssystem, ob und wie bereits Kontakt bestand. Bei weiterem Bedarf kann ein Gespräch angeboten werden.",
        "next_step_shared": "Bei einem gemeinsamen Sachproblem kann ein freiwilliger Gruppentermin helfen. Teile keine individuelle Prüfliste mit der Gruppe.",
        "next_step_record": "Halte tatsächlich erfolgte Kontakte und Vereinbarungen im geschützten Betreuungssystem fest, damit nicht versehentlich mehrfach angesprochen wird. Die App versendet nichts und führt keinen Kontaktstatus.",
        "contact_limit": "Dieser Prototyp speichert keine Gespräche oder Bearbeitungsstände. „Schon früher auf Liste“ beschreibt nur einen früheren Modellhinweis in dieser Datei.",
        "manager_title": "Leitung & Kapazität",
        "manager_intro": "Plane, wie viel Betreuung eine Prüfliste an diesem Kurstag ungefähr auslösen könnte. Die Angaben sind frei wählbare Szenarien und keine tatsächlich geführten Kontakte.",
        "manager_scope": "Umfang der Prüflisten in allen Kursen",
        "manager_short": "Kürzere Listen · rund 10 % je Kurs",
        "manager_extended": "Erweiterte Listen · rund 20 % je Kurs",
        "manager_scope_help": "Jeder Kurs wird für diesen Kurstag getrennt betrachtet und auf ganze Einträge aufgerundet. Die 20-%-Liste enthält auch die Einträge aus der 10-%-Liste.",
        "manager_scenario": "Annahmen für diese Woche",
        "manager_review_min": "Minuten für die fachliche Sichtung je Listeneintrag",
        "manager_email_pct": "Für welchen Anteil eine Nachricht eingeplant wird (%)",
        "manager_email_min": "Minuten je geprüfter Nachricht",
        "manager_call_pct": "Für welchen Anteil ein Gespräch eingeplant wird (%)",
        "manager_call_min": "Minuten je Gespräch einschließlich Vorbereitung",
        "manager_hours_coach": "Verfügbare Stunden je Coach für diese Aufgabe in der Woche",
        "manager_assumptions": "E-Mail- und Gesprächsanteile sind Planungsannahmen, keine vom Modell ermittelten Schwellen. Dieselbe Person kann beides erhalten. Kontakte werden je Kurs auf ganze Personen aufgerundet; die Zeit ist eine Schätzung.",
        "manager_selected": "Einträge auf Prüflisten",
        "manager_first": "Davon erstmals in Datei",
        "manager_first_unknown": "Frühere Hinweise unbekannt",
        "manager_hours": "Geschätzte Stunden",
        "manager_coaches": "Benötigte Coach-Kapazitäten",
        "manager_coaches_help": "Geschätzte Stunden geteilt durch die je Coach für diese Aufgabe verfügbare Wochenzeit, auf ganze Personen aufgerundet. Das ist keine Personalbedarfsberechnung für eine reale Einrichtung.",
        "manager_chart": "Geschätzter Aufwand nach Kurs",
        "manager_table": "Kurse im Vergleich",
        "manager_course": "Kurs",
        "manager_entries": "Angemeldet",
        "manager_hints": "Auf Liste",
        "manager_new": "Erstmals in Datei",
        "manager_repeat": "Früher in Datei",
        "manager_due": "Davon offene fällige Leistung",
        "manager_emails": "Nachrichten geplant",
        "manager_calls": "Gespräche geplant",
        "manager_course_hours": "Stunden geschätzt",
        "manager_history": "Erstmals/früher bedeutet nur: in den Wochen dieser CSV auf der gewählten 10-%- oder 20-%-Liste. Es sagt nichts über gesendete Nachrichten aus.",
        "manager_history_missing": "Für diesen Kurstag enthält die Datei keine frühere Modellwoche. Erstmalige und wiederholte Hinweise lassen sich daher nicht unterscheiden.",
        "manager_limits": "Die CSV enthält keine späteren Kursergebnisse oder dokumentierten Kontakte. Die Ansicht zeigt weder tatsächlich Betreute noch verhinderte Abbrüche. Wenn du zu einer anderen Woche wechselst, entsteht ein neues Szenario; addiere die Wochenzahlen nicht als verschiedene Personen.",
        "manager_method": "So setzt sich der Zeitbedarf zusammen",
        "manager_formula": "Aufwand = Sichtungen × Minuten je Sichtung + geplante Nachrichten × Minuten je Nachricht + geplante Gespräche × Minuten je Gespräch. Innerhalb jedes Kurses werden die geplanten Kontakte auf ganze Personen aufgerundet. Der Wert berücksichtigt keine weiteren Aufgaben oder ungeplanten Rückfragen.",
        "manager_no_roles": "Die Ansichten sind im Prototyp nicht durch Benutzerrollen getrennt. Für einen Einsatz mit echten Teilnehmendendaten wären getrennte Zugriffsrechte erforderlich.",
        "draft_title": "Neutrale Nachricht als Entwurf anzeigen",
        "draft_label": "Text zum Prüfen und Kopieren",
        "draft_text": "Hallo, wie kommst du derzeit im Kurs zurecht? Gibt es etwas, wobei wir dich unterstützen können? Wenn du möchtest, können wir uns dazu kurz austauschen. Viele Grüße",
        "draft_limit": "Die Vorlage wird nur angezeigt und nicht versendet. Ergänze Anrede und Namen selbst und prüfe den Text vor einer möglichen Kontaktaufnahme. Er nennt kein Modell und behauptet keine persönliche Ursache.",
        "report_button": "Kursbericht herunterladen",
        "report_help": "Ein lokal gespeicherter, druckbarer HTML-Bericht für den gerade gewählten Kurs, Kurstag und Listenfilter. Er enthält anonymisierte IDs und sollte geschützt aufbewahrt werden.",
        "report_title": "Kursbericht",
        "report_snapshot": "Stand: Tag {day} · {course}",
        "report_numbers": "{n} Einträge im Kurs · {selected} auf der gewählten Prüfliste · {due} davon mit offener fälliger Leistung",
        "report_note": "Auswahl zur fachlichen Sichtung, keine Entscheidung oder Diagnose. Beobachtungen sind keine individuellen Ursachen. Dieser Bericht enthält anonymisierte IDs und bleibt lokal.",
        "report_print": "Im Browser öffnen und bei Bedarf als PDF drucken.",
        "report_scope": "Gewählte Liste",
        "report_file": "kursbericht_tag_{day}_{course}.html",
    },
    "en": {
        "tagline": "Weekly review to support learner conversations",
        "language": "Language / Sprache",
        "help_button": "Help & background",
        "help_title": "Help and project background",
        "help_quick": "How to use it & glossary",
        "help_background": "About the demo",
        "help_start": "How to use this view",
        "help_steps": "1. Upload a prepared weekly CSV and choose a course day.\n2. Review a course list and choose suitable support.\n3. Use the Management section to plan time for reviews, messages and conversations. Record actual contacts in the designated support system.",
        "glossary": "Glossary",
        "limitations": "What this prototype cannot tell you",
        "limits_text": "The model ranks course entries for a combined later outcome: withdrawal or failure. It does not reliably identify the type of difficulty for an individual. Recorded clicks and submissions do not explain a person's situation; the effect of outreach has not been tested. The historical OULAD models are not validated for other training settings.",
        "theme_help": "Light or dark mode: Open the Streamlit menu (⋮) at the top right, then Settings → Theme. To enlarge text, use browser zoom (Ctrl and +). Check the layout at 200% zoom too.",
        "gloss_csv": "CSV: a text file containing tabular data. This app requires the prepared weekly format.",
        "gloss_vle": "VLE (Virtual Learning Environment): the online learning platform. Clicks reflect recorded use, not study time or understanding.",
        "gloss_assessment": "Assessment: a scheduled course assignment. An item is open if no own or credited completion is recorded by its due date.",
        "gloss_entry": "Course entry: a person's participation in a particular course presentation. One person can have multiple entries.",
        "gloss_course": "Course presentation: one module in a specific run, for example BBB 2014J.",
        "gloss_hint": "Review list: a selection for professional review. 10% or 20% describes how many people from a course are selected on this day (rounded up for small courses). It is not a fixed risk threshold. People outside the list can also withdraw or fail.",
        "gloss_first": "New on list: this entry did not appear on the currently selected short or extended list in an earlier week of the uploaded CSV. Already on list before: it appeared on that type of list earlier. The app does not know whether anyone was contacted.",
        "gloss_ap": "AP (Average Precision): evaluates how well later cases rank near the top overall. A model evaluation measure, not an individual score.",
        "gloss_recall": "Recall: the share of all later cases included in the review list. A model evaluation measure.",
        "gloss_score": "Model score: an internal value used to rank entries within a course; not a validated individual failure probability here.",
        "bug_button": "Report a bug",
        "bug_title": "Prepare a bug report",
        "bug_intro": "Describe what went wrong. The report is downloaded locally and is not sent automatically.",
        "bug_expected": "What did you expect?",
        "bug_observed": "What happened instead?",
        "bug_steps": "How can the issue be reproduced?",
        "bug_privacy": "Do not enter names, learner IDs, course files, or other personal data. A public GitHub issue is unsuitable for such data.",
        "bug_download": "Download bug report",
        "bug_missing": "First describe what happened.",
        "bug_issue": "Open GitHub issue (optional)",
        "data_title": "Provide data",
        "change_data": "Change file",
        "data_intro": "Upload a prepared weekly CSV. For the demo, download the example file and then select it here.",
        "demo_download": "Download demo file",
        "upload_label": "Select weekly CSV",
        "upload_help": "One row per enrolled course entry and course day. A complete course is needed for a full review list. Raw OULAD files must be prepared first.",
        "no_upload": "After uploading, choose a course day and open the review lists.",
        "load_spinner": "Checking file and calculating alerts …",
        "model_error": "Model evaluation failed. See the terminal for details.",
        "upload_error": "The uploaded file could not be processed. Technical details are shown below.",
        "technical_details": "Technical details (currently in German)",
        "loaded": "{n} weekly records loaded from {file}.",
        "day_label": "Select course day",
        "day_option": "Day {day} · week {week}",
        "history_unknown": "The file contains no earlier week for this course day. We cannot tell whether someone appeared on a review list previously.",
        "history_known": "New on list = not on the selected short or extended list in an earlier week of this file. Already on list before = on that type of list earlier. The app does not know whether any conversations took place.",
        "nav": "Section",
        "nav_week": "🗓️ This week",
        "nav_course": "👥 Review a course",
        "nav_manager": "📊 Management & capacity",
        "nav_background": "📚 About the project",
        "week_intro": "Choose a course whose alerts you want to review.",
        "metric_entries": "Current course entries",
        "metric_courses": "Courses",
        "metric_hints": "On review lists",
        "metric_hints_help": "Top 20% of course entries within each course presentation, rounded up to whole people.",
        "col_course": "Course",
        "col_entries": "Course entries",
        "col_review": "For review",
        "col_first": "New on list",
        "col_repeat": "Already on list before",
        "col_first_help": "These course entries had no alert in any earlier week of the uploaded file.",
        "col_repeat_help": "These course entries had an alert in at least one earlier week of the uploaded file. This says nothing about contact with a learner.",
        "col_due": "With open due work",
        "col_due_help": "At least one due assessment without recorded own or credited completion.",
        "col_review_help": "Top 20% in the model ranking for this course; not a fixed risk threshold.",
        "course_choose": "Course for the review list",
        "open_list": "Open review list",
        "trend_open": "Review lists by week (all courses)",
        "trend_intro": "Each row shows how many course entries were on a review list for the first time in this file or had already appeared in an earlier uploaded week.",
        "trend_day": "Course day",
        "trend_caption": "The same person may appear in several weeks. Do not add up these rows as distinct people. Contact and conversations are not recorded here.",
        "course_title": "Review a course",
        "course_label": "Course presentation",
        "course_caution": "The list supports professional review. An alert is not a diagnosis or a validated personal failure probability.",
        "scope_label": "How many people will you review?",
        "scope_more": "Review more people: {n} of {total} (roughly the top 20%)",
        "scope_less": "Review fewer people: {n} of {total} (roughly the top 10%)",
        "scope_help": "The 10% list includes the highest-ranked entries in this course on this day. The 20% list includes the same entries and the next group. Small courses are rounded up. Each week is evaluated again: over multiple weeks, more than 20% may receive an alert at some point.",
        "scope_caption": "You see {n} of {total} people in this course. The remaining {remaining} are not on today's list, but they might still withdraw or fail. The percentage limits how many people you review now; it is not a personal probability of failure.",
        "scope_evidence_title": "How many later cases did the lists find in the historical comparison?",
        "scope_evidence": "On day 27 in 2014J, the 20% lists included 1,006 of 2,947 later cases (34.1%). Another 1,941 later cases were not on a list that day. The 10% lists included 595 cases (20.2%). This is an exploratory historical evaluation, not a promise for this course or another provider. Repeated weekly reviews do not replace professional judgement.",
        "filter_label": "Show alerts",
        "filter_all": "All",
        "filter_first": "New on list",
        "filter_repeat": "Already on list before",
        "list_summary": "{n} of {total} course entries on this review list.",
        "list_empty": "No alerts match this filter on the selected day.",
        "col_id": "Anonymous ID",
        "col_group": "Review group",
        "group_high": "Review first",
        "group_more": "Further review",
        "col_status": "List history in file",
        "status_first": "New on list",
        "status_repeat": "Already on list before",
        "status_unknown": "No earlier weekly record",
        "status_none": "No alert",
        "col_id_help": "Anonymous identifier for a course entry; the app has no name.",
        "col_group_help": "Model ranking within this course presentation; not a diagnosis.",
        "col_status_help": "New means no appearance on the currently selected type of list in an earlier week of this CSV. Already on list before means at least one earlier appearance on that list. It does not tell you about contact with a learner.",
        "col_missing": "Due work without completion",
        "col_clicks": "Platform clicks in last 7 days",
        "col_clicks_help": "Recorded VLE clicks in the last seven course days; not a measure of study time or understanding.",
        "person_choose": "Review one person",
        "detail_title": "ID {id} · observations by day {day}",
        "due_observation": "{n} due assessment(s) without recorded submission or credit.",
        "due_question": "Was the work submitted, credited, or still under review?",
        "zero_observation": "No recorded platform clicks in the last seven days.",
        "zero_question": "Were there access issues or learning outside the platform?",
        "low_observation": "Fewer platform clicks than this course's median in the last seven days.",
        "no_observation": "None of these simple individual indicators stands out. The model uses a combination of inputs.",
        "conversation": "Points to check in a supportive conversation",
        "general_question": "What support would the learner find useful?",
        "detail_limit": "These observations do not explain the model score or the person's situation. Withdrawal and failure are predicted together.",
        "next_step_title": "Choose a next step",
        "next_step_first": "Review this entry with professional judgement. If support would be useful, start with a short, neutral message offering help.",
        "next_step_due": "First check whether the due work is truly outstanding. If the learner wants support or an assignment needs timely clarification, offer a personal conversation.",
        "next_step_repeat": "This entry appeared on a review list in an earlier uploaded week. First check the support system for previous contact. If help is still needed, offer a conversation.",
        "next_step_shared": "An optional group session may help with a shared course issue. Never share an individual review list with the group.",
        "next_step_record": "Record actual contacts and agreements in the protected support system to avoid accidental repeat outreach. This app sends nothing and does not track contacts.",
        "contact_limit": "This prototype does not store conversations or case status. 'Already on list before' describes only an earlier model alert in this file.",
        "manager_title": "Management & capacity",
        "manager_intro": "Explore how much support a review list might require on this course day. These are adjustable planning scenarios, not records of actual outreach.",
        "manager_scope": "Size of the review lists across courses",
        "manager_short": "Short lists · roughly 10% per course",
        "manager_extended": "Extended lists · roughly 20% per course",
        "manager_scope_help": "Each course is considered separately on this day and rounded up to whole entries. The 20% list also contains all entries on the 10% list.",
        "manager_scenario": "Assumptions for this week",
        "manager_review_min": "Minutes to review each listed entry",
        "manager_email_pct": "Share planned to receive a message (%)",
        "manager_email_min": "Minutes per reviewed message",
        "manager_call_pct": "Share planned for a conversation (%)",
        "manager_call_min": "Minutes per conversation including preparation",
        "manager_hours_coach": "Hours available per coach for this task this week",
        "manager_assumptions": "Message and conversation shares are planning assumptions, not model thresholds. A learner can receive both. Contact numbers are rounded up within each course; time is an estimate.",
        "manager_selected": "Entries on review lists",
        "manager_first": "First listed in this file",
        "manager_first_unknown": "Earlier alerts unknown",
        "manager_hours": "Estimated hours",
        "manager_coaches": "Coach capacity required",
        "manager_coaches_help": "Estimated hours divided by time available per coach for this task, rounded up to whole people. This is not a staffing calculation for a real provider.",
        "manager_chart": "Estimated effort by course",
        "manager_table": "Courses at a glance",
        "manager_course": "Course",
        "manager_entries": "Enrolled",
        "manager_hints": "On list",
        "manager_new": "First listed in file",
        "manager_repeat": "Listed earlier in file",
        "manager_due": "With outstanding due work",
        "manager_emails": "Messages planned",
        "manager_calls": "Conversations planned",
        "manager_course_hours": "Estimated hours",
        "manager_history": "First/earlier refers only to the chosen 10% or 20% list in the weeks of this CSV. It does not indicate whether a message was sent.",
        "manager_history_missing": "The file contains no earlier model week for this day, so first and repeat alerts cannot be distinguished.",
        "manager_limits": "The CSV has no later outcomes or contact records. This view shows neither people actually supported nor withdrawals prevented. Changing the selected week creates a new scenario; do not add weekly counts as distinct people.",
        "manager_method": "How effort is estimated",
        "manager_formula": "Effort = reviews × minutes per review + planned messages × minutes per message + planned conversations × minutes per conversation. Planned contacts are rounded up within each course. This does not include other tasks or unexpected replies.",
        "manager_no_roles": "This prototype does not enforce user roles between views. Real learner data would require separate access rights.",
        "draft_title": "Show a neutral message draft",
        "draft_label": "Text to review and copy",
        "draft_text": "Hello, how are things going in your course? Is there anything we can help you with? If you would like to talk, we can arrange a short conversation. Best wishes,",
        "draft_limit": "This is only a draft and is not sent. Add the person's name yourself and review the text before any outreach. It does not mention the model or claim to know the person's situation.",
        "report_button": "Download course report",
        "report_help": "A locally saved, printable HTML report for the selected course, day, and list filter. It contains anonymous IDs and should be stored securely.",
        "report_title": "Course report",
        "report_snapshot": "As of day {day} · {course}",
        "report_numbers": "{n} entries in course · {selected} on selected review list · {due} with open due work",
        "report_note": "A list for professional review, not a decision or diagnosis. Observations are not individual causes. This report includes anonymous IDs and remains local.",
        "report_print": "Open in a browser and print to PDF if needed.",
        "report_scope": "Selected list",
        "report_file": "course_report_day_{day}_{course}.html",
    },
}


def tr(language: str, key: str, **values) -> str:
    """Liest einen Oberflächentext und setzt optionale Zahlen und Namen ein."""
    return TEXT[language][key].format(**values)


def local_group(language: str, value: str) -> str:
    """Übersetzt die internen Prüfgruppen nur für die Anzeige."""
    key = {
        "Hohe Priorität": "group_high",
        "Weitere Prüfung": "group_more",
        "Kein Hinweis": "status_none",
    }.get(value)
    return tr(language, key) if key else value


def local_status(language: str, value: str) -> str:
    """Übersetzt den internen Wochenstatus nur für die Anzeige."""
    key = {
        "Erstmals im Upload": "status_first",
        "Wiederholt im Upload": "status_repeat",
        "Ohne Verlauf": "status_unknown",
        "Kein Hinweis": "status_none",
    }.get(value)
    return tr(language, key) if key else value


def local_upload_error(language: str, message: str) -> str:
    """Übersetzt bekannte CSV-/Modellmeldungen für den englischen Modus."""
    if language == "de":
        return message
    prefixes = {
        "Die CSV konnte nicht gelesen werden: ": "Could not read the CSV: ",
        "Diese Spalten fehlen: ": "Missing required columns: ",
        "Leere Kurskennung in ": "Empty course identifier in ",
        "Für diese Stichtage gibt es kein Modell: ": "No model for these course days: ",
        "Für diese Module gibt es keine Trainingsdaten: ": "No training data for these modules: ",
    }
    full = {
        "Die CSV enthält keine Kurseinträge.": "The CSV contains no course entries.",
        "Benötigte Spalten enthalten leere Werte.": "Required columns contain empty values.",
        "Stichtag, Anmeldung, Klicks und Assessments müssen Zahlen sein.":
            "Course day, registration, clicks and assessments must be numbers.",
        "Stichtage müssen ganze Kurstage sein.": "Course days must be whole numbers.",
        "Ein Kurseintrag wurde erst nach seinem Stichtag angemeldet.":
            "A course entry was registered after its course day.",
        "Klicks und Assessmentzahlen dürfen nicht negativ sein.":
            "Click and assessment counts must not be negative.",
        "Klicks und Assessmentzahlen müssen ganze Zahlen sein.":
            "Click and assessment counts must be whole numbers.",
        "Fehlende Assessments übersteigen die fälligen Assessments.":
            "Missing assessments exceed due assessments.",
        "Klicks der letzten Woche übersteigen die gesamten Klicks.":
            "Last-week clicks exceed total clicks.",
        "Ein Kurseintrag steht am selben Stichtag mehrfach in der CSV.":
            "A course entry appears more than once for the same day.",
    }
    if message in full:
        return full[message]
    if message.startswith("Das Modell für Tag "):
        value = message.removeprefix("Das Modell für Tag ")
        if " fehlt: " in value:
            day, file = value.split(" fehlt: ", 1)
            return f"Missing model for day {day}: {file}"
        if value.endswith(" hat keine positive Klasse 1."):
            day = value.removesuffix(" hat keine positive Klasse 1.")
            return f"The model for day {day} has no positive class 1."
        if value.endswith(" lieferte ungültige Werte."):
            day = value.removesuffix(" lieferte ungültige Werte.")
            return f"The model for day {day} returned invalid values."
    for source, target in prefixes.items():
        if message.startswith(source):
            return target + message.removeprefix(source)
    return tr(language, "upload_error")
